name: build - macos
on:
  workflow_call:

jobs:
  macos:
    strategy:
      matrix:
        config: [debug, release]
        compiler: [clang]
    name: MacOS ${{ matrix.config }} ${{ matrix.compiler }}
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Installing dependencies
      run: |
        export ICU_ROOT="$(brew --prefix icu4c)" && \
        export PATH="/usr/local/opt/ccache/libexec:/usr/local/opt/gettext/bin:$PATH";
        ./install-dependencies.sh homebrew ccache dylibbundler
    - name: show compiler failures clearly on github
      uses: ammaraskar/gcc-problem-matcher@0.2.0
      # clang reports problems the same way
    - name: Building
      run: |
        mkdir build_wl
        cd build_wl/
        ../utils/macos/build_app.sh "--${{ matrix.config }}" "--${{ matrix.compiler }}"
        echo ::remove-matcher owner=gcc-problem-matcher:: # removes the problem matcher
        grep -v REVDETECT-BROKEN ../build/VERSION
        DMGPATH="$(pwd)"
        DMGFILE="$(ls *.dmg)"
        echo "DMG file is: $DMGPATH/$DMGFILE"
        mv "$DMGFILE" "${{ github.workspace }}/Widelands-${{ github.sha }}-${{ matrix.config }}-${{ matrix.compiler }}.dmg"

    - name: Uploading DMG
      uses: actions/upload-artifact@v3
      with:
        name: Widelands ${{ matrix.config }} ${{ matrix.compiler }} MacOS 11 AppImage
        path: ${{ github.workspace }}/Widelands-${{ github.sha }}-${{ matrix.config }}-${{ matrix.compiler }}.dmg
